### ISSUE TITLE
[SERVICE] add CellDesigner as tool/service

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/cloud#10]
# CellDesigner

* Does the service require a login? YES / NO
* Technology Readiness Level (TRL)?
* API Type? REST | SOAP | other
* Who are the targeted users?
* Relevant VHP4Safety Case Study?

## Specification

* Provided by? WHO IS PROVIDING THE SERVICE?
* Citation? PUT HERE A DOI
* Version?
* License?
* Source Code?
* Docker?
* ELIXIR Bio.tools?
* ELIXIR TeSS?

**Comment by ozancinar** [comment]
The JSON file has been created and the associated markdown file can be found [here](https://github.com/VHP4Safety/cloud/blob/main/docs/service/celldesigner.md).
