### ISSUE TITLE
[SERVICE] add FLame as tool/service

### ISSUE THREAD

**Issue by tabbassidaloii** [VHP4Safety/cloud#11]
# Flame

* Does the service require a login? NO
* Technology Readiness Level (TRL)?
* API Type? REST | SOAP | other
* Who are the targeted users?
* Relevant VHP4Safety Case Study?

## Specification

* Provided by? WHO IS PROVIDING THE SERVICE?
* Citation? [DOI](https://doi.org/10.1186/s13321-021-00509-z)
* Version?
* [License?](https://github.com/phi-grib/flame/blob/master/LICENSE)
* Source Code?
* Docker?
* ELIXIR Bio.tools?
* ELIXIR TeSS?

**Comment by egonw** [comment]
Lead author on this paper is Prof. Sanz who is also member of the ELIXIR Tox Community and involved in projects like eTRANSAFE.

**Comment by egonw** [comment]
The web UI can be found here: https://github.com/phi-grib/flame_API

**Comment by egonw** [comment]
Catalog record here: https://cloud.vhp4safety.nl/service/flame.html
