### ISSUE TITLE
[SERVICE] Docking and SOM prediction

### ISSUE THREAD

**Issue by thepoole** [VHP4Safety/cloud#13]
Please fill out the below form as complete as possible, but empty fields can be filled out later. 

#  Docking and SOM prediction (a trifunctional microservice)
A repackaged version of the SOM/SmartCYP2.0/PLANTS microservice from OpenRiskNet (https://openrisknet.org/e-infrastructure/services/126/). This provides SOM prediction by docking or machine learning approaches for multiple cyp450 isoforms. In addition, the docking functionality can be called separately, producing protein-ligand complexes using PLANTS1.2.

* Does the service require a login? No
* Technology Readiness Level (TRL)? Integrated application
* API Type? REST
* Who are the targeted users? Researchers in metabolomics, biochemistry
* Relevant VHP4Safety Case Study?

## Specification
Docking-based SOM prediction
* Provided by? Vrije University Amsterdam
* Citation? 
* Version? 1.0.1 alpha
* License? Apache 2.0
* Source Code? Yes (https://github.com/MD-Studio/MDStudio)
* Docker? Yes
* ELIXIR Bio.tools?
* ELIXIR TeSS?

PLANTS Docking
* Provided by? Universität Konstanz
* Citation? J. Chem. Inf. Model. 2009, 49, 1, 84–96
* Version? 1.2 x64
* License? 
* Source Code? No.
* Docker? Yes
* ELIXIR Bio.tools?
* ELIXIR TeSS?

SmartCYP2.0
* Provided by?  University of Copenhagen
* Citation? ACS Med. Chem. Lett. 2010, 1, 3, 96–100
* Version? 2.0
* License? Apache 2.0
* Source Code? No.
* Docker? Yes
* ELIXIR Bio.tools?
* ELIXIR TeSS?

**Comment by ozancinar** [comment]
Deployed and a URL has been created on [https://sombie.cloud.vhp4safety.nl/](https://sombie.cloud.vhp4safety.nl/). Could you please check the information [here](https://github.com/VHP4Safety/cloud/blob/main/docs/index.md) and
[here](https://github.com/VHP4Safety/cloud/blob/main/docs/service/sombie.md) and let me know if they need to be updated?

**Comment by egonw** [comment]
The two pages look like a good start to me. After the deliverable we can slowly focus on completeness of the metadata (like tutorials listed, etc).
