### ISSUE TITLE
[SERVICE] TXG-MAPr

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/cloud#14]
# TXG-MAPr

https://txg-mapr.eu/

* Does the service require a login? YES
* Technology Readiness Level (TRL)? Unsure
* API Type? none
* Who are the targeted users?
* Relevant VHP4Safety Case Study?

## Specification

* Provided by? Leiden University
* Citation? https://link.springer.com/article/10.1007/s00204-021-03141-w
* Version?
* License? Proprietary
* Source Code? Proprietary
* Docker? Yes
* ELIXIR Bio.tools?
* ELIXIR TeSS?

**Comment by ozancinar** [comment]
It's been added to the catalog.
