### ISSUE TITLE
new CDK Depict docker

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/cloud#16]
CDK Depict 1.9.3 is out (3 days): https://hub.docker.com/layers/simolecule/cdkdepict/1.9.3/images/sha256-810be305f0a3397358b8f2a4589faf29ce2316eee5586479ef48a277a7647e6a?context=explore

**Comment by ozancinar** [comment]
It has been deployed on the server.

**Comment by egonw** [comment]
Looks to be working as expected.
