### ISSUE TITLE
[SERVICE] Add AOP portal on WikiPathways

### ISSUE THREAD

**Issue by marvinm2** [VHP4Safety/cloud#18]
Please fill out the below form as complete as possible, but empty fields can be filled out later. 

# molecular AOP portal on WikiPathways

* Does the service require a login? NO
* Technology Readiness Level (TRL)? 
* API Type? REST | SOAP | other
* Who are the targeted users?
* Relevant VHP4Safety Case Study? All of them

## Specification

* Provided by? UM
* Citation? -
* Version? -
* License? WikiPathways license: CC0
* Source Code?
* Docker? No
* ELIXIR Bio.tools? https://bio.tools/wikipathways
* ELIXIR TeSS?

**Comment by marvinm2** [comment]
Yes, that's the URL. Also, for citation it can be this one until a better one: https://www.frontiersin.org/articles/10.3389/fgene.2018.00661/abstract

**Comment by egonw** [comment]
@marvinm2, can you tomorrow perhaps create a Markdown page like https://github.com/VHP4Safety/cloud/blob/main/docs/service/wikibase.md (or any other one in the folder)?

**Comment by ozancinar** [comment]
A [page](https://github.com/VHP4Safety/cloud/blob/main/docs/service/wikipathways_aop.md) has been created and an item has been added to the [service list](https://github.com/VHP4Safety/cloud/blob/main/docs/index.md).
