### ISSUE TITLE
[SERVICE] PopGen

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/cloud#23]
# PopGen

Virtual Human Population Generator

* External: http://xnet.hsl.gov.uk/Popgen/
* Does the service require a login? no
* Technology Readiness Level (TRL)?
* API Type? [SOAP](http://xnet.hsl.gov.uk/Popgen/service.aspx)
* Who are the targeted users? Researchers
* Relevant VHP4Safety Case Study?

## Specification

* Provided by? [UK Health and Safety Laboratory](http://www.hsl.gov.uk/)
* Citation? 
* Version?
* License?
* Source Code?
* Docker?
* ELIXIR Bio.tools?
* ELIXIR TeSS?

**Comment by ozancinar** [comment]
It is added to the index and catalog along with its [markdown page](https://github.com/VHP4Safety/cloud/blob/main/docs/service/popgen.md)
