### ISSUE TITLE
Add BioModels to the VHP4Safety cloud

### ISSUE THREAD

**Issue by ElenaDR1** [VHP4Safety/cloud#25]
Please fill out the below form as complete as possible, but empty fields can be filled out later. 

# BioModels

* Does the service require a login? NO
* Technology Readiness Level (TRL)?
* API Type? REST | SOAP | other
* Who are the targeted users? Project partners (Model group and VHP creators), and modelling community in general
* Relevant VHP4Safety Case Study? BioModels is a large open access repository for mathematical biological models. The models developed within VHP4Safety could be added to BioModels.

## Specification

* Provided by? Open access tool, by EMBL-EBI (https://www.ebi.ac.uk/biomodels/)
* Citation? https://doi.org/10.1093/nar/gkz1055.  
* Version?
* License?
* Source Code?
* Docker?
* ELIXIR Bio.tools? Yes
* ELIXIR TeSS? Yes (https://www.ebi.ac.uk/training/events/exploring-reproducible-and-reusable-systems-biology-models-biomodels/)

**Comment by egonw** [comment]
I added a JSON configuration file (https://github.com/VHP4Safety/cloud/blob/main/docs/service/biomodels.json) which created this Markdown file with the new GitHub Action: https://github.com/VHP4Safety/cloud/blob/main/docs/service/biomodels.md

**Comment by egonw** [comment]
ELIXIR info is added too now.
