### ISSUE TITLE
[SERVICE] JRC Data Catalogue

### ISSUE THREAD

**Issue by ElenaDR1** [VHP4Safety/cloud#31]
Please fill out the below form as complete as possible, but empty fields can be filled out later. 

# Joint Research Centre (JRC) Data Catalogue
Data repository which may be useful for the sustainability of project results. It is managed by the EU Joint Research Centre.

* Does the service require a login? NO
* Technology Readiness Level (TRL)?
* API Type? REST | SOAP | other
* Who are the targeted users? WP1.1, and Data Management team.
* Relevant VHP4Safety Case Study? General interest, not necessarily specific.

## Specification

* Provided by? WHO IS PROVIDING THE SERVICE? the EU Joint Research Centre
* Citation? EU-ToxRisk. (2020). EU-ToxRisk:  An Integrated European 'Flagship' Program Driving Mechanism-based Toxicity Testing and Risk Assessment for the 21st Century. Deliverable 3.4: Repository of in silico methods. R1 – 14/02/2020
* Version?
* License?
* Source Code?
* Docker?
* ELIXIR Bio.tools?
* ELIXIR TeSS?

**Comment by ozancinar** [comment]
The REST API to access the data is described [here](https://data.jrc.ec.europa.eu/about#services). 

Maybe it's possible for us to find a way to use the API from our servers.

**Comment by ozancinar** [comment]
The JSON file has been created and the associated markdown file can be found [here](https://github.com/VHP4Safety/cloud/blob/main/docs/service/jrc_data_catalogue.md).

**Comment by ElenaDR1** [comment]
ok, thank you!
