### ISSUE TITLE
identify which OpenRiskNet services we want to put online in Autumn 2022

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/cloud#4]
See https://openrisknet.org/e-infrastructure/services/

**Comment by egonw** [comment]
ping @marvinm2 @ozancinar, what do you think?

**Comment by marvinm2** [comment]
Toxcast/tox21, EdelweissData (or the TG-GATESDrugmatrix service, or ToxicoDB)for data access
jaqpot for PBPK??
Lazar (QSAR)

**Comment by Chris-Evelo** [comment]
Apart from which we want to have we also need to discuss for which ones we do the initial ones and which ones can be installed from containers already updated by other EOSC platform partners OpenTox and Ola. I think we need to plan a meeting with them.

**Comment by ozancinar** [comment]
Shall we aim for all the services shown ([here](https://openrisknet.org/e-infrastructure/services/?q=&category=predictive-toxicology&service_type=&user_type=&targeted_user=)) when filtering the services for predictive toxicology?
