### ISSUE TITLE
[SERVICE] FAIRspace

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/cloud#46]
# FAIRspace

An open source (meta)data platform that also allows import/export of metadata and uses RDF (turtle) underneath.

Below is to be looked up:

* Does the service require a login? YES / NO
* Technology Readiness Level (TRL)?
* API Type? REST | SOAP | other
* Who are the targeted users?
* Relevant VHP4Safety Case Study?

## Specification

* Provided by? WHO IS PROVIDING THE SERVICE?
* Citation? PUT HERE A DOI
* Version?
* License?
* Source Code?
* Docker?
* ELIXIR Bio.tools?
* ELIXIR TeSS?

**Comment by egonw** [comment]
cc @Chris-Evelo

**Comment by Chris-Evelo** [comment]
I asked Duygu to fill this in, since she has hands-on experience

**Comment by egonw** [comment]
Thanks, @dygdedesener!

@ozancinar, can you use this to create a markdown entry?

**Comment by ozancinar** [comment]
Created here: [json](https://github.com/VHP4Safety/cloud/blob/main/docs/service/fairspace.json), [md](https://github.com/VHP4Safety/cloud/blob/main/docs/service/fairspace.md).
