### ISSUE TITLE
Issue with the action to create the markdown files

### ISSUE THREAD

**Issue by ozancinar** [VHP4Safety/cloud#73]
The issue has occurred first after [this commit](https://github.com/VHP4Safety/cloud/commit/0775b92044b841343d0ecd32973e305392ed1b28) where [the json file for the AOP-Wiki API](https://github.com/VHP4Safety/cloud/blob/main/docs/service/aopwikiapi.json) was added. 

The issue was that the action to create the markdown files [failed](https://github.com/VHP4Safety/cloud/actions/runs/10582973371/job/29358118496). The following message was prompted in the output of the action which might give a hint about:

```
The current character read is '/' with an int value of 47
Unable to determine the current character, it is not a string, number, array, or object
line number 2
index number 1
// This is a template for JSON files that can provide a standard way to add 
^
groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
```

I do not know where this issue stems from, i.e. i) from an (syntax) issue in the json file; ii) in the groovy files to create the markdown files; or iii) in the github action. Because, between when the action worked the last time and when this issue occurred first, most changes have been made in the [action file](https://github.com/VHP4Safety/cloud/blob/main/.github/workflows/create-markdown.yml) during two ([1](https://github.com/VHP4Safety/cloud/commit/5008f5f15cab0a8d531948e74a8e6ae02a969425), [2](https://github.com/VHP4Safety/cloud/commit/78cc891e7c0e01b3198fb2310270e5f93e772c88)) commits. So, it might be happening due to the changes in the workflow itself, rather than the groovy files or the json file.

**Comment by egonw** [comment]
Yeah, it seems to be the comment line from the template. JSON comments don't work like that. In fact, they don't really support it, see https://stackoverflow.com/questions/244777/can-comments-be-used-in-json

**Comment by egonw** [comment]
Okay, I was able to confirm it. I removed the comment lines and now it seems to work again.
