### ISSUE TITLE
review issue template

### ISSUE THREAD

**Issue by egonw** [VHP4Safety/cloud#74]
For new tools: https://github.com/VHP4Safety/cloud/issues/new?assignees=&labels=service&projects=&template=new-tool-service-entry-new.yml&title=%5BSERVICE%5D%3A+

Ozan, can you please give me feedback?

**Comment by ozancinar** [comment]
I created [a pull request](https://github.com/VHP4Safety/cloud/pull/75) with a modified yml file with my feedback. I tried to add items to ask for service description a URL to the service and an email address of the provider. 

These aside, I converted the case study to regulatory questions and, tried, to give a link to the regulatory questions list in the docs repo. 

Please feel free to merge or reject this pull request, if the changes are not well.
